[project]
name = "routing-comparison-nwm-nextgen-troute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9, <=3.12"
dependencies = [
    "argparse>=1.4.0",
    "datetime>=6.0",
    "numpy<2.5.1",
    "nwmurl>=1.0.6",
    "pandas>=3.0.5",
    "pathlib>=1.0.1",
    "xarray>=2026.7.0",
]
