# -*- coding: utf-8 -*-
"""visualizing_outputs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yo1qJTg3QtLiDwdkRQyR4fsGq0ArC8uz

## **Comparing NWM and Routing-Only datastream (and t-route)**

## Imports
"""

import xarray as xr
import pandas as pd
import json
import matplotlib.pyplot as plt
import ipywidgets as widgets
from numpy import select
import itertools
import matplotlib.cm as cm

"""## NWM"""

# NWM dataset
# base_path = '/content/drive/MyDrive/Research/June19th04/'
base_path = '/content/drive/MyDrive/Research/Apr30th00/'

# first_nwm_filename = f'{base_path}nwm.t04z.short_range.channel_rt.f001.conus.nc'
first_nwm_filename = f'{base_path}nwm.t00z.short_range.channel_rt.f001.conus.nc'
with xr.open_dataset(first_nwm_filename) as ds_first:
    base_forecast_time = pd.to_datetime(ds_first.attrs['model_initialization_time'], format='%Y-%m-%d_%H:%M:%S', utc=True)

nwm_streamflows = []
for i in range(1, 19):
    hr_num = str(i).zfill(3) # Ensures f001, f002, ... format
    # filename = f'nwm.t04z.short_range.channel_rt.f{hr_num}.conus.nc'
    filename = f'nwm.t00z.short_range.channel_rt.f{hr_num}.conus.nc'
    ds = xr.open_dataset(base_path + filename)
    streamflow_da = ds['streamflow']

    valid_time = base_forecast_time + pd.Timedelta(hours=i)

    # Expand dimensions to add 'time' and assign the correct valid_time
    streamflow_da = streamflow_da.expand_dims(time=[valid_time])
    nwm_streamflows.append(streamflow_da)

nwm_flow = xr.concat(nwm_streamflows, dim='time')

"""## NextGen Routing-Only"""

# NextGen Routing-only dataset
# df_ro = pd.read_parquet ('/content/drive/MyDrive/Research/June19th04/troute_output_202606190500.parquet')
df_ro = pd.read_parquet ('/content/drive/MyDrive/Research/Apr30th00/troute_output_202604300100.parquet')
# Ensure 'time' column is UTC-aware before setting as index
df_ro['time'] = pd.to_datetime(df_ro['time'], utc=True)
df_ro = df_ro.set_index(['feature_id', 'time'])
ds_ro = df_ro.to_xarray()
ro_flow = ds_ro['flow']

# Crosswalk NWM and NextGen IDs
with open('/content/drive/MyDrive/Research/nwm_to_ngen_map.json', 'r') as f:
  mapping_dict = json.load(f)
convert_id = pd.Series(mapping_dict)

# print(convert_id['nex-492001'])

"""## T-Route"""

# t_route
# df_t_route = pd.read_parquet('/content/drive/MyDrive/Research/June19th04/flowveldepth_2026-07-01T13:05:35.034852.parquet')
df_t_route = pd.read_parquet('/content/drive/MyDrive/Research/Apr30th00/flowveldepth_2026-07-01T11:03:51.645850.parquet')
df_t_route['value_time'] = pd.to_datetime(df_t_route['value_time'], utc=True)
df_t_route = df_t_route.set_index(['location_id','value_time'])

"""## Gage Data"""

# Gage data
walnut_gage = pd.read_excel('/content/drive/MyDrive/Research/Apr30th00/walnut creek gage data.xlsx', usecols=['time', 'value'])
mulberry_gage = pd.read_excel('/content/drive/MyDrive/Research/Apr30th00/mulberry_creek_gage.xlsx', usecols=['time', 'value'])
cahaba_gage = pd.read_excel('/content/drive/MyDrive/Research/Apr30th00/cahaba river gage data.xlsx', usecols=['time', 'value'])

"""## Data Retrieval


"""

# data retrieval
def get_comparison_data(id, zero_threshold=0.2, selected_gage_df=None):

    ro_series = ro_flow.sel(feature_id=id).to_pandas()

    nwm_ids_raw = convert_id.get(f'nex-{str(id)}', [])
    filtered_nwm_data_dict = {} # Stores {nwm_id: nwm_series}
    filtered_nwm_ids = []
    nwm_series_list = []

    troute_data_dict = {} # Stores {troute_id: troute_series}
    troute_series_list = [] # For calculating the mean

    nwm_mean_series = None
    if nwm_ids_raw:
        for n_id in nwm_ids_raw:
            nwm_individual_series = nwm_flow.sel(feature_id=n_id).to_pandas() # Get series directly
            if not nwm_individual_series.empty and nwm_individual_series.max() > zero_threshold:
                filtered_nwm_ids.append(n_id)
                filtered_nwm_data_dict[f'nwm_flow_{int(n_id)}'] = nwm_individual_series
                nwm_series_list.append(nwm_individual_series)

        if nwm_series_list:
            # Concatenate series into a DataFrame and calculate mean along columns
            nwm_mean_series = pd.concat(nwm_series_list, axis=1, join='outer').mean(axis=1)

    if filtered_nwm_ids:
        for n_id in filtered_nwm_ids:
            troute_location_id = f'nex-{int(n_id)}'
            try:
                troute_streamflow_series = df_t_route.loc[(troute_location_id, slice(None)), :]
                troute_streamflow_series = troute_streamflow_series[troute_streamflow_series['variable_name'] == 'streamflow']['value']
                if not troute_streamflow_series.empty:
                    troute_streamflow_series = troute_streamflow_series.reset_index(level='location_id', drop=True)
                    troute_streamflow_series.index = pd.to_datetime(troute_streamflow_series.index)
                    # troute_streamflow_series_hourly = troute_streamflow_series.resample('h').mean()
                    if not troute_streamflow_series.isnull().all():
                        troute_data_dict[f't_route_{int(n_id)}'] = troute_streamflow_series
                        troute_series_list.append(troute_streamflow_series)
            except KeyError:
                pass

    troute_mean_series = None
    if troute_series_list:
        # Concatenate series into a DataFrame and calculate mean along columns
        troute_mean_series = pd.concat(troute_series_list, axis=1, join='outer').mean(axis=1)

    # Process gage data
    gage_data_series = None
    if selected_gage_df is not None and not selected_gage_df.empty:
        gage_df = selected_gage_df.copy()
        gage_df['time'] = pd.to_datetime(gage_df['time'], utc=True)
        gage_df = gage_df.set_index('time').sort_index()

        # Filter gage data for the requested time range.
        # start_time = pd.Timestamp('2026-06-19 04:00:00', tz='UTC')
        # end_time = pd.Timestamp('2026-06-19 22:00:00', tz='UTC')
        start_time = pd.Timestamp('2026-04-30 00:00:00', tz='UTC')
        end_time = pd.Timestamp('2026-04-30 19:00:00', tz='UTC')
        gage_df = gage_df.loc[start_time:end_time]
        gage_data_series = gage_df['value'] * 0.0283168 # convert to metric

    return ro_series, filtered_nwm_data_dict, nwm_mean_series, troute_data_dict, troute_mean_series,  gage_data_series

"""##Make Plot"""

def plot_data(id, zero_threshold=0.2, selected_gage_df=None):
    plt.figure(figsize=(12, 7))

    ro_series, filtered_nwm_data_dict, nwm_mean_series, troute_data_dict, troute_mean_series, gage_data_series = \
        get_comparison_data(id, zero_threshold, selected_gage_df=selected_gage_df)

    # Colors for NWM and t_route
    nwm_colors = plt.cm.YlOrRd([0.3, 0.5, 0.7, 0.9])
    troute_colors = plt.cm.GnBu([0.3, 0.5, 0.7, 0.9])

    # Plot gage data
    if gage_data_series is not None and not gage_data_series.isnull().all():
        plt.plot(gage_data_series.index, gage_data_series.values, label='Gage Data', color='purple', linewidth=2, linestyle='-')

    # Plot NextGen routing-only
    plt.plot(ro_series.index, ro_series.values, label=f'NextGen {id}', color='black', linewidth=2)

    # Plot individual NWM
    nwm_color_cycle = itertools.cycle(nwm_colors)
    sorted_nwm_labels = sorted(filtered_nwm_data_dict.keys())
    for nwm_label in sorted_nwm_labels:
        nwm_individual_series = filtered_nwm_data_dict[nwm_label]
        nwm_id = int(nwm_label.replace('nwm_flow_', ''))
        plt.plot(nwm_individual_series.index, nwm_individual_series.values, label=f'NWM {nwm_id}', color=next(nwm_color_cycle), linestyle='--', alpha=0.7, linewidth=0.75)

    # Plot individual t_route
    troute_color_cycle = itertools.cycle(troute_colors)
    sorted_troute_labels = sorted(troute_data_dict.keys())
    for troute_label in sorted_troute_labels:
        troute_individual_series = troute_data_dict[troute_label]
        troute_nwm_id = int(troute_label.replace('t_route_', ''))
        plt.plot(troute_individual_series.index, troute_individual_series.values, label=f't_route {troute_nwm_id}', color=next(troute_color_cycle), linestyle='-', alpha=0.7, linewidth=0.75)

    # NWM average
    if nwm_mean_series is not None:
        plt.plot(nwm_mean_series.index, nwm_mean_series.values, label='NWM Average', color='red', linewidth=4, linestyle='-')

    # t-route average
    if troute_mean_series is not None:
        plt.plot(troute_mean_series.index, troute_mean_series.values, label='t_route Average', color='darkgreen', linewidth=5, linestyle='--')

    # Formatting
    title_components = [f'Flow Comparison for nex-{id}']
    plt.title(' '.join(title_components))
    plt.xlabel('Time')
    plt.ylabel('Flow Rate (m^3/s)')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

"""##Combine to one DataFrame"""

def combine_data_frames(id, zero_threshold=0.2, selected_gage_df=None):
    ro_series, filtered_nwm_data_dict, nwm_mean_series, troute_data_dict, troute_mean_series, gage_data_series = \
        get_comparison_data(id, zero_threshold, selected_gage_df=selected_gage_df)

    # Create a list of all series to merge
    all_series = []
    all_series.append(ro_series.rename('routing-only'))
    if troute_mean_series is not None:
        all_series.append(troute_mean_series.rename('t_route_flow_average'))
    if nwm_mean_series is not None:
        all_series.append(nwm_mean_series.rename('nwm_flow_average'))
    if gage_data_series is not None:
        all_series.append(gage_data_series.rename('gage_data'))

    for nwm_label, nwm_individual_series in filtered_nwm_data_dict.items():
        all_series.append(nwm_individual_series.rename(nwm_label))
    for troute_label, troute_individual_series in troute_data_dict.items():
        all_series.append(troute_individual_series.rename(troute_label))

    # Merge all series using their indices with an outer join to keep all time points
    flow_comparison = pd.concat(all_series, axis=1, join='outer')

    # Filter to only include 'on the hour' timestamps
    flow_comparison = flow_comparison[flow_comparison.index.minute == 0]

    return flow_comparison

"""## Show plot & dataframe"""

def show_combined_info():
  id_str = input("Enter a NextGen ID: ")
  full_id_key = f'nex-{id_str}'
  if full_id_key in convert_id.index:
    id = int(id_str)
  else:
    print(f"Invalid ID number: {id_str}")
    return

  selected_gage_df = None
  if id == 497369:
      selected_gage_df = walnut_gage
  elif id == 497368:
      selected_gage_df = walnut_gage
  elif id == 492001:
      selected_gage_df = mulberry_gage
  elif id == 492000:
      selected_gage_df = mulberry_gage
  elif id == 491344:
      selected_gage_df = cahaba_gage
  elif id == 491343:
      selected_gage_df = cahaba_gage

  plot_data(id, selected_gage_df=selected_gage_df)
  print("\nCombined Flow Comparisons:")
  pd.set_option('display.max_columns', None) # display all columns.
  pd.set_option('display.max_rows', None)
  display(combine_data_frames(id, selected_gage_df=selected_gage_df))

  return

"""# Plots
Walnut Creek: 497369, 497368\
Mulberry Creek: 492001, 492000\
Cahaba River: 491344, 491343
"""

show_combined_info()

