# -*- coding: utf-8 -*-
"""nwm_to_ngen.py

Automatically generated by Colab. Written by Aubrey Kohler. Edited by Quinn Lee Russell

Original file is located at
    https://colab.research.google.com/drive/1yo1qJTg3QtLiDwdkRQyR4fsGq0ArC8uz

Takes routed outputs from t-route on the National Water Model (NWM) hydrofabric, converts them to
the NextGen hydrofabric.
"""

import json
import argparse
from pathlib import Path
import pandas as pd

def _parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--nwm_to_ngen_map",
        type=Path,
        help="Path to the nwm_to_ngen_map.json"
    )
    parser.add_argument(
        "--troute_outputs",
        type=Path,
        help="Path to the NWM t-route outputs"
    )

    args = parser.parse_args()
    return args

def main():
    """Takes the mean of flow, velocity, and depth for all NWM routed outputs that correspond to a
    NextGen catchment, and creates a file that looks like a t-route output but with NextGen IDs.
    """
    args = _parse_arguments()

    # Crosswalk NWM and NextGen IDs
    with open(args.nwm_to_ngen_map, "r", encoding="utf-8") as f:
        mapping_dict = json.load(f) # {nex-id: [nwm_id_1, nwm_id_2, ...]}

    troute_filepath = args.troute_outputs

    # t_route
    df_t_route = pd.read_parquet(
        troute_filepath
    )

    # Map and aggregate
    df_t_route['feature_id'] = df_t_route['location_id'].str.replace('nex-', '').astype(float)
    # Create reverse mapping
    id_to_cat = {fid: cat for cat, fids in mapping_dict.items() for fid in fids}
    df_t_route['catchment'] = df_t_route['feature_id'].map(id_to_cat)

    # Group by category, timestep, and variable, then average
    ngen_output = df_t_route.groupby(['catchment', 'value_time', 'variable_name']).agg({
        'value': 'mean',
        'units': 'first',
        'reference_time': 'first',
        'configuration': 'first'
    }).reset_index()

    # Rename category to location_id
    ngen_output = ngen_output.rename(columns={'catchment': 'location_id'})

    ngen_output_path = troute_filepath.with_stem(f"converted_{troute_filepath.stem}")
    ngen_output.to_parquet(ngen_output_path)

if __name__ == "__main__":
    main()
